### ISSUE TITLE
Do you think you will be a programmer forever?

### ISSUE THREAD

**Issue by CarlMungazi** [Qix-/ama#11]

**Comment by Qix-** [comment]
Hmm that's a hard question to answer.

On one front I think I'll always program. I might not identify as a programmer, simply because I don't see myself doing programming _professionally_ all my life (programming hasn't been challenging for me for a while now).

I've often thought about going to school for something along the lines of chemistry. Being in a lab full time 'discovering' things is one of those "That would be cool!" things that I finally decided I should pursue.

So while I'll always bring a computer science element to whatever I'm doing, you probably won't see me calling myself a programmer in 20 years.

Good question!
