### ISSUE TITLE
Do you believe in extraterrestrial life?

### ISSUE THREAD

**Issue by robbbz** [Qix-/ama#8]

**Comment by Qix-** [comment]
Yes. The probability of Earth being the only life-sustaining body in the universe (observable or otherwise) is unrealistically low. Do I believe they've actually visited Earth? Probably not. If the speed of light is truly the fastest achievable speed of any particle, communications reaching from here to another body could take longer than the life of Earth itself. Therefore, another intelligent species being aware of our existence is pretty slim in that case.

**tl;dr** yes.

**Comment by Qix-** [comment]
Good question :)
